version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.6-management
    # ports: ['15672:15672']
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'unless-stopped'

  lib:
    image: node:14
    command: sleep infinity
    working_dir: /workspace
    depends_on:
      - rabbitmq
    environment:
      AMQP_DSN: amqp://rabbitmq/
    volumes:
      - .:/workspace:delegated
      - ~/.bash_history:/root/.bash_history
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'no'
